In [ ]:
# Microfinance Fraud Detection using Machine Learning

## Data Understanding

### Objective

The objective of this notebook is to understand the structure of the dataset before performing any preprocessing or machine learning.

In this notebook we will:

- Load the dataset
- Understand its structure
- Check rows and columns
- Identify data types
- Check missing values
- Check duplicate records
- View statistical summary
- Analyze the target variable

No preprocessing or model training is performed in this notebook.

In [1]:
#import Required Libraries

import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
print("Libraries imported successfully!")

Libraries imported successfully!

In [3]:
#Load the dataset

df = pd.read_csv('C:\\Users\\Dinesh\\OneDrive\\Desktop\\Microfinance-Fraud-Detection\\data\\raw\\microfinance_fraud_detection_dataset.csv')
print("Dataset loaded successfully!")
print(f"Dataset shape: {df.shape}")

Dataset loaded successfully!
Dataset shape: (50000, 125)

In [4]:
df.head()

,transaction_id,customer_id,branch_id,loan_id,customer_age,gender,marital_status,education_level,occupation,annual_income,monthly_expenses,credit_score,years_with_institution,previous_loan_count,dependents,home_ownership,residential_stability_years,mobile_registered,email_registered,region,district,village,distance_to_branch_km,branch_transaction_volume,branch_fraud_rate_history,loan_purpose,requested_amount,approved_amount,disbursed_amount,loan_term_months,interest_rate,loan_to_income_ratio,interest_rate_type,collateral_provided,collateral_type,guarantors_count,group_lending,group_size,application_channel,processing_time_days,document_verification_score,scheduled_installment,actual_installment_paid,payment_frequency,days_overdue,missed_payments,total_payments_made,payment_method,remaining_balance,debt_service_ratio,payment_consistency,savings_balance,avg_monthly_transactions,avg_transaction_amount,total_transaction_volume,transaction_velocity,cash_out_percentage,suspicious_transaction_count,late_night_transactions,international_transactions,high_value_transaction_flag,transaction_amount_std,unusual_transaction_ratio,rounding_amount_percentage,app_login_frequency,app_login_anomaly_score,device_changes,ip_changes,sim_card_changes,account_age_days,failed_login_attempts,biometric_verification,account_shared,password_changes,blacklist_match,duplicate_application,identity_verification_failed,kyc_completeness,sanctions_screening,pep_flag,aml_alert_count,reference_check_result,income_verification_method,income_discrepancy,social_connections,fraudster_connections,same_address_users,same_bank_account_users,network_risk_score,referral_source,typing_speed_anomaly,click_pattern_anomaly,session_duration_anomaly,navigation_pattern_score,loan_status,days_since_disbursement,npv_score,bureau_score,recovery_amount,write_off_amount,application_date,disbursement_date,application_day_of_week,application_hour,income_stability_score,employment_tenure_years,loan_utilization_ratio,credit_utilization_ratio,active_loans_count,total_debt_obligation,financial_dependency_ratio,loan_renewal_count,penalty_charges,late_payment_fee_total,customer_complaint_count,customer_satisfaction_score,field_officer_id,field_officer_experience,officer_approval_tendency,weather_index,crop_yield_estimate,political_stability_index,inflation_rate,exchange_rate,is_fraud
0,TXN000001,CUST01825,BR049,LOAN04822,43,Male,Divorced,Diploma,Retired,45591.89,36846.86,549,6.79,2,0,Rented,3.13,True,False,Urban,District_32,Village_466,14.50,3566,0.0611,Health,31726.53,28333.91,25248.05,24,31.81,7.4576,Variable,False,NaN,0,True,11,Mobile App,26.93,89.99,1556.12,1465.70,Weekly,0,5,7,Bank Transfer,15407.91,0.4096,0.6374,209.64,8,6130.88,588564.48,24.32,73.12,0,1,False,False,2092.40,0.1259,65.11,12,0.1683,2,4,0,1297,2,False,False,1,False,False,False,57.22,Clear,False,0,Partial,Self-Declared,False,11,1,0,0,0.4138,Social Media,0.0534,0.4932,0.9701,0.4524,Defaulted,606,97.31,315,18629.86,0.0,2024-05-25,2024-06-12,Saturday,11,0.6904,0.56,0.7958,1.0740,1,47749.92,1.0473,0,0.0,0.0,2,2.54,FO063,17.83,0.5002,8.96,26.47,5.84,9.39,192.98,0
1,TXN000002,CUST00410,BR174,LOAN05235,36,Male,Married,Primary,Farmer,75316.77,50231.18,654,0.36,6,2,Owned,10.71,True,True,Rural,District_49,Village_191,0.90,7135,0.0924,Consumption,23345.72,22350.25,18643.59,18,20.64,3.5610,Fixed,False,NaN,0,True,9,Agent/Field Officer,22.12,7.10,1497.96,999.59,Monthly,0,0,10,Cash,14736.34,0.2387,0.6897,6788.34,9,13278.44,1434071.52,29.22,46.69,0,1,False,False,1030.43,0.3782,45.39,21,0.4853,1,2,2,1468,3,True,False,4,False,False,False,88.99,Flagged,False,1,Verified,Tax Return,False,24,1,0,0,0.5990,Employee,0.7677,0.2630,0.0175,0.8145,Active,248,70.49,605,0.00,0.0,2023-05-07,2023-06-03,Sunday,21,0.2918,2.38,0.7986,0.7902,1,77179.82,1.0247,0,0.0,0.0,2,4.12,FO064,18.08,0.9391,47.29,9.84,3.65,3.13,128.14,0
2,TXN000003,CUST04507,BR163,LOAN07508,45,Female,Married,PhD,Small Business Owner,53905.76,48578.39,522,2.34,0,2,Owned,3.61,True,False,Semi-Urban,District_47,Village_38,0.35,5693,0.1022,Agriculture,39331.28,22151.17,19589.73,6,28.84,4.9311,Fixed,False,NaN,3,True,3,Phone,40.27,27.23,4756.59,5238.70,Weekly,0,4,26,Check,0.00,1.0589,0.4695,1958.14,6,35279.85,2540149.20,30.24,88.02,3,2,False,False,467.38,0.3260,69.70,12,0.7904,0,0,0,1122,0,True,False,1,False,False,False,31.77,Clear,False,0,Verified,Bank Statement,False,14,1,1,2,0.9875,Employee,0.3987,0.2776,0.2105,0.8110,Defaulted,87,35.18,637,16180.19,0.0,2024-08-25,2024-09-18,Sunday,18,0.9838,8.66,0.4981,0.0585,1,69546.20,1.2901,0,0.0,0.0,3,3.05,FO062,11.60,0.9008,54.84,34.80,1.59,15.60,53.54,0
3,TXN000004,CUST04013,BR158,LOAN12869,56,Female,Single,Secondary,Self-Employed,34222.08,28662.02,643,4.09,2,0,Owned,3.72,True,True,Remote Rural,District_38,Village_14,1.52,2981,0.0582,Small Business,15556.34,12885.24,12817.28,12,16.84,4.5182,Variable,False,NaN,1,False,0,Phone,30.18,15.26,1254.59,797.38,Weekly,0,2,28,Mobile Money,0.00,0.4399,0.4734,3623.41,8,4604.27,442009.92,16.99,72.36,0,2,False,False,1744.62,0.3467,10.56,21,0.2951,2,1,0,706,1,False,False,0,False,False,True,77.03,Pending,False,2,Verified,Self-Declared,False,17,2,1,0,0.7872,Social Media,0.4831,0.0905,0.1856,0.4695,Active,486,72.05,693,0.00,0.0,2024-01-19,2024-02-07,Friday,14,0.3844,3.37,0.8239,0.3610,4,45810.69,1.3386,1,0.0,0.0,1,4.16,FO065,9.34,0.7004,15.10,40.09,4.78,14.76,93.30,1
4,TXN000005,CUST03658,BR021,LOAN06457,35,Male,Divorced,Secondary,Salaried Employee,89250.89,52902.34,592,9.07,4,1,Rented,15.81,True,True,Semi-Urban,District_18,Village_275,0.10,8840,0.1093,Agriculture,55943.55,44986.40,44969.24,3,11.88,6.0485,Variable,False,NaN,0,False,0,Agent/Field Officer,21.25,33.26,16776.93,24206.96,Monthly,0,0,34,Direct Debit,0.00,2.2557,0.2064,353.71,6,7251.18,522084.96,18.08,8.54,0,1,False,False,8216.04,0.1113,68.46,19,0.6241,1,6,0,267,1,True,False,2,False,False,False,99.42,Clear,False,1,Verified,Bank Statement,False,11,2,0,4,0.9397,Walk-in,0.0320,0.2557,0.3000,0.1910,Active,368,56.97,618,0.00,0.0,2024-08-25,2024-09-22,Sunday,21,0.4005,4.13,0.8038,1.0179,1,44494.35,0.4985,2,0.0,0.0,0,3.90,FO072,11.71,0.8055,23.54,32.68,3.07,9.91,191.42,0

In [5]:
#dataset shape

rows,cols = df.shape
print(f"Number of rows: {rows}")
print(f"Number of columns: {cols}")

Number of rows: 50000
Number of columns: 125

In [7]:
# ============================================================
# Step 5 : Display Columns
# ============================================================

for i, col in enumerate(df.columns, start=1):
    print(f"{i}. {col}")

1. transaction_id
2. customer_id
3. branch_id
4. loan_id
5. customer_age
6. gender
7. marital_status
8. education_level
9. occupation
10. annual_income
11. monthly_expenses
12. credit_score
13. years_with_institution
14. previous_loan_count
15. dependents
16. home_ownership
17. residential_stability_years
18. mobile_registered
19. email_registered
20. region
21. district
22. village
23. distance_to_branch_km
24. branch_transaction_volume
25. branch_fraud_rate_history
26. loan_purpose
27. requested_amount
28. approved_amount
29. disbursed_amount
30. loan_term_months
31. interest_rate
32. loan_to_income_ratio
33. interest_rate_type
34. collateral_provided
35. collateral_type
36. guarantors_count
37. group_lending
38. group_size
39. application_channel
40. processing_time_days
41. document_verification_score
42. scheduled_installment
43. actual_installment_paid
44. payment_frequency
45. days_overdue
46. missed_payments
47. total_payments_made
48. payment_method
49. remaining_balance
50. debt_service_ratio
51. payment_consistency
52. savings_balance
53. avg_monthly_transactions
54. avg_transaction_amount
55. total_transaction_volume
56. transaction_velocity
57. cash_out_percentage
58. suspicious_transaction_count
59. late_night_transactions
60. international_transactions
61. high_value_transaction_flag
62. transaction_amount_std
63. unusual_transaction_ratio
64. rounding_amount_percentage
65. app_login_frequency
66. app_login_anomaly_score
67. device_changes
68. ip_changes
69. sim_card_changes
70. account_age_days
71. failed_login_attempts
72. biometric_verification
73. account_shared
74. password_changes
75. blacklist_match
76. duplicate_application
77. identity_verification_failed
78. kyc_completeness
79. sanctions_screening
80. pep_flag
81. aml_alert_count
82. reference_check_result
83. income_verification_method
84. income_discrepancy
85. social_connections
86. fraudster_connections
87. same_address_users
88. same_bank_account_users
89. network_risk_score
90. referral_source
91. typing_speed_anomaly
92. click_pattern_anomaly
93. session_duration_anomaly
94. navigation_pattern_score
95. loan_status
96. days_since_disbursement
97. npv_score
98. bureau_score
99. recovery_amount
100. write_off_amount
101. application_date
102. disbursement_date
103. application_day_of_week
104. application_hour
105. income_stability_score
106. employment_tenure_years
107. loan_utilization_ratio
108. credit_utilization_ratio
109. active_loans_count
110. total_debt_obligation
111. financial_dependency_ratio
112. loan_renewal_count
113. penalty_charges
114. late_payment_fee_total
115. customer_complaint_count
116. customer_satisfaction_score
117. field_officer_id
118. field_officer_experience
119. officer_approval_tendency
120. weather_index
121. crop_yield_estimate
122. political_stability_index
123. inflation_rate
124. exchange_rate
125. is_fraud

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Columns: 125 entries, transaction_id to is_fraud
dtypes: bool(13), float64(52), int64(33), str(27)
memory usage: 43.3 MB

In [ ]:
## Missing Values Analysis

#Missing values reduce data quality and can affect model performance.  
#This section checks whether the dataset contains any missing values.

In [10]:
#check missing values in the dataset

missing_values = df.isnull().sum()
missing_df = pd.DataFrame({
    "Column": missing_values.index,
    "Missing Values": missing_values.values
})

missing_df = missing_df[missing_df["Missing Values"] > 0]

if missing_df.empty:
    print("No Missing Values Found")
else:
    display(missing_df.sort_values(by="Missing Values", ascending=False))

             Column  Missing Values
34  collateral_type           29898

In [ ]:
### Observation

#The dataset is checked for missing values.  
#The result will help determine whether data cleaning is required before model training.

In [11]:
#check duplicate records in the dataset

duplicate_records = df.duplicated().sum()
print(f"Number of duplicate records: {duplicate_records}")

Number of duplicate records: 0

In [13]:
#statistical summary of the dataset

df.describe().T

,count,mean,std,min,25%,50%,75%,max
customer_age,50000.0,37.762780,11.452916,18.00,29.0000,38.000,46.000,80.00
annual_income,50000.0,49268.755009,42573.657077,1200.00,21153.4950,36279.005,62178.000,250000.00
monthly_expenses,50000.0,33249.962626,30432.378850,608.66,13486.2525,23773.215,41916.375,236150.89
credit_score,50000.0,647.917800,98.370049,300.00,581.0000,649.000,716.000,850.00
years_with_institution,50000.0,3.014100,2.992990,0.10,0.8700,2.110,4.160,25.00
...,...,...,...,...,...,...,...,...
crop_yield_estimate,50000.0,49.876062,28.902439,0.00,24.6300,49.940,74.840,99.99
political_stability_index,50000.0,5.023397,2.891385,0.00,2.5200,5.020,7.540,10.00
inflation_rate,50000.0,13.493610,6.629619,2.00,7.7800,13.460,19.240,25.00
exchange_rate,50000.0,125.145773,43.296852,50.00,87.6900,125.150,162.590,200.00
is_fraud,50000.0,0.170000,0.375637,0.00,0.0000,0.000,0.000,1.00

In [ ]:
## Categorical Columns

#This section identifies all categorical features in the dataset.

In [14]:
#Categorical Colums

categorical_columns = df.select_dtypes(include=["object"]).columns

print(f"Total Categorical Columns : {len(categorical_columns)}\n")

for col in categorical_columns:
    print(col)

Total Categorical Columns : 27

transaction_id
customer_id
branch_id
loan_id
gender
marital_status
education_level
occupation
home_ownership
region
district
village
loan_purpose
interest_rate_type
collateral_type
application_channel
payment_frequency
payment_method
sanctions_screening
reference_check_result
income_verification_method
referral_source
loan_status
application_date
disbursement_date
application_day_of_week
field_officer_id

C:\Users\Dinesh\AppData\Local\Temp\ipykernel_31524\1014782391.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include=["object"]).columns

In [ ]:
##Numerical Columns

#this section identifies all numerical features in the dataset.

In [15]:
numerical_columns = df.select_dtypes(include=["int64", "float64"]).columns

print(f"Total Numerical Columns : {len(numerical_columns)}\n")

for col in numerical_columns:
    print(col)

Total Numerical Columns : 85

customer_age
annual_income
monthly_expenses
credit_score
years_with_institution
previous_loan_count
dependents
residential_stability_years
distance_to_branch_km
branch_transaction_volume
branch_fraud_rate_history
requested_amount
approved_amount
disbursed_amount
loan_term_months
interest_rate
loan_to_income_ratio
guarantors_count
group_size
processing_time_days
document_verification_score
scheduled_installment
actual_installment_paid
days_overdue
missed_payments
total_payments_made
remaining_balance
debt_service_ratio
payment_consistency
savings_balance
avg_monthly_transactions
avg_transaction_amount
total_transaction_volume
transaction_velocity
cash_out_percentage
suspicious_transaction_count
late_night_transactions
transaction_amount_std
unusual_transaction_ratio
rounding_amount_percentage
app_login_frequency
app_login_anomaly_score
device_changes
ip_changes
sim_card_changes
account_age_days
failed_login_attempts
password_changes
kyc_completeness
aml_alert_count
social_connections
fraudster_connections
same_address_users
same_bank_account_users
network_risk_score
typing_speed_anomaly
click_pattern_anomaly
session_duration_anomaly
navigation_pattern_score
days_since_disbursement
npv_score
bureau_score
recovery_amount
write_off_amount
application_hour
income_stability_score
employment_tenure_years
loan_utilization_ratio
credit_utilization_ratio
active_loans_count
total_debt_obligation
financial_dependency_ratio
loan_renewal_count
penalty_charges
late_payment_fee_total
customer_complaint_count
customer_satisfaction_score
field_officer_experience
officer_approval_tendency
weather_index
crop_yield_estimate
political_stability_index
inflation_rate
exchange_rate
is_fraud

In [16]:
#target variable analysis

target_counts = df["is_fraud"].value_counts()

print(target_counts)

print("\nPercentage Distribution:\n")

print((df["is_fraud"].value_counts(normalize=True) * 100).round(2))

is_fraud
0    41500
1     8500
Name: count, dtype: int64

Percentage Distribution:

is_fraud
0    83.0
1    17.0
Name: proportion, dtype: float64