# Microfinance Fraud Detection using Machine Learning

## Data Preprocessing

### Objective

This notebook prepares the dataset for machine learning by cleaning the data, removing unnecessary features, encoding categorical variables, scaling numerical variables, and splitting the dataset into training and testing sets.

### Tasks

- Load dataset
- Remove unnecessary columns
- Handle missing values
- Handle duplicates
- Feature selection
- Encode categorical features
- Scale numerical features
- Train-test split

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv(r"C:\Users\Dinesh\OneDrive\Desktop\Microfinance-Fraud-Detection\data\raw\microfinance_fraud_detection_dataset.csv")
print(df.shape)
df.head()

(50000, 95)

,transaction_id,customer_id,branch_id,loan_id,customer_age,gender,marital_status,education_level,occupation,annual_income,...,income_stability_score,employment_tenure_years,credit_utilization_ratio,active_loans_count,total_debt_obligation,financial_dependency_ratio,savings_balance,penalty_charges,fraud_type,is_fraud
0,TXN000001,CUST01825,BR049,LOAN04822,43,Male,Divorced,Diploma,Retired,45591.89,...,0.7108,25.09,0.3091,1,70864.38,1.5543,366.27,2.69,Not Fraud,0
1,TXN000002,CUST00410,BR174,LOAN05235,36,Male,Married,Primary,Farmer,75316.77,...,0.5664,2.49,0.0835,2,76609.22,1.0172,3837.05,0.00,Not Fraud,0
2,TXN000003,CUST04507,BR163,LOAN07508,45,Female,Married,PhD,Small Business Owner,53905.76,...,0.7840,2.72,0.6358,1,97220.41,1.8035,698.63,0.00,Not Fraud,0
3,TXN000004,CUST04013,BR158,LOAN12869,56,Female,Single,Secondary,Self-Employed,34222.08,...,0.6262,12.82,0.2256,4,36526.56,1.0673,2177.94,0.00,Not Fraud,0
4,TXN000005,CUST03658,BR021,LOAN06457,35,Male,Divorced,Secondary,Salaried Employee,89250.89,...,0.8419,14.37,1.0249,2,150323.27,1.6843,13883.37,0.00,Not Fraud,0

In [4]:
df.isnull().sum()

transaction_id                0
customer_id                   0
branch_id                     0
loan_id                       0
customer_age                  0
                             ..
financial_dependency_ratio    0
savings_balance               0
penalty_charges               0
fraud_type                    0
is_fraud                      0
Length: 95, dtype: int64

In [5]:
print("Duplicate Rows :", df.duplicated().sum())

Duplicate Rows : 0

In [6]:
df = df.drop_duplicates()

print(df.shape)

(50000, 95)

In [10]:
drop_columns = [
    "customer_id",
    "loan_id",
    
    "transaction_id"
]

df.drop(columns=drop_columns, inplace=True)

df.head()

,branch_id,customer_age,gender,marital_status,education_level,occupation,annual_income,monthly_expenses,credit_score,years_with_institution,...,income_stability_score,employment_tenure_years,credit_utilization_ratio,active_loans_count,total_debt_obligation,financial_dependency_ratio,savings_balance,penalty_charges,fraud_type,is_fraud
0,BR049,43,Male,Divorced,Diploma,Retired,45591.89,36846.86,563,6.79,...,0.7108,25.09,0.3091,1,70864.38,1.5543,366.27,2.69,Not Fraud,0
1,BR174,36,Male,Married,Primary,Farmer,75316.77,50231.18,663,0.36,...,0.5664,2.49,0.0835,2,76609.22,1.0172,3837.05,0.00,Not Fraud,0
2,BR163,45,Female,Married,PhD,Small Business Owner,53905.76,48578.39,544,2.34,...,0.7840,2.72,0.6358,1,97220.41,1.8035,698.63,0.00,Not Fraud,0
3,BR158,56,Female,Single,Secondary,Self-Employed,34222.08,28662.02,637,4.09,...,0.6262,12.82,0.2256,4,36526.56,1.0673,2177.94,0.00,Not Fraud,0
4,BR021,35,Male,Divorced,Secondary,Salaried Employee,89250.89,52902.34,613,9.07,...,0.8419,14.37,1.0249,2,150323.27,1.6843,13883.37,0.00,Not Fraud,0

In [11]:
post_loan_features = [
    "fraud_type"
]

df.drop(columns=post_loan_features, inplace=True)

df.head()

,branch_id,customer_age,gender,marital_status,education_level,occupation,annual_income,monthly_expenses,credit_score,years_with_institution,...,application_hour,income_stability_score,employment_tenure_years,credit_utilization_ratio,active_loans_count,total_debt_obligation,financial_dependency_ratio,savings_balance,penalty_charges,is_fraud
0,BR049,43,Male,Divorced,Diploma,Retired,45591.89,36846.86,563,6.79,...,18,0.7108,25.09,0.3091,1,70864.38,1.5543,366.27,2.69,0
1,BR174,36,Male,Married,Primary,Farmer,75316.77,50231.18,663,0.36,...,16,0.5664,2.49,0.0835,2,76609.22,1.0172,3837.05,0.00,0
2,BR163,45,Female,Married,PhD,Small Business Owner,53905.76,48578.39,544,2.34,...,18,0.7840,2.72,0.6358,1,97220.41,1.8035,698.63,0.00,0
3,BR158,56,Female,Single,Secondary,Self-Employed,34222.08,28662.02,637,4.09,...,9,0.6262,12.82,0.2256,4,36526.56,1.0673,2177.94,0.00,0
4,BR021,35,Male,Divorced,Secondary,Salaried Employee,89250.89,52902.34,613,9.07,...,18,0.8419,14.37,1.0249,2,150323.27,1.6843,13883.37,0.00,0

In [12]:
X = df.drop("is_fraud", axis=1)

y = df["is_fraud"]

In [13]:
categorical_columns = X.select_dtypes(include=["object"]).columns

categorical_columns

C:\Users\Dinesh\AppData\Local\Temp\ipykernel_29156\3973694625.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = X.select_dtypes(include=["object"]).columns

Index(['branch_id', 'gender', 'marital_status', 'education_level',
       'occupation', 'home_ownership', 'region', 'state', 'loan_purpose',
       'application_channel', 'device_type', 'browser_type', 'network_type',
       'payment_frequency', 'payment_method', 'sanctions_screening',
       'reference_check_result', 'loan_status', 'application_date',
       'application_day_of_week'],
      dtype='str')

In [14]:
numerical_columns = X.select_dtypes(exclude=["object"]).columns

numerical_columns

Index(['customer_age', 'annual_income', 'monthly_expenses', 'credit_score',
       'years_with_institution', 'previous_loan_count', 'dependents',
       'mobile_registered', 'distance_to_branch_km',
       'branch_transaction_volume', 'branch_fraud_rate_history',
       'requested_amount', 'approved_amount', 'disbursed_amount',
       'loan_term_months', 'interest_rate', 'loan_to_income_ratio',
       'collateral_provided', 'guarantors_count', 'group_lending',
       'processing_time_days', 'scheduled_installment',
       'actual_installment_paid', 'days_overdue', 'missed_payments',
       'total_payments_made', 'remaining_balance', 'debt_service_ratio',
       'payment_consistency', 'avg_monthly_transactions',
       'avg_transaction_amount', 'total_transaction_volume',
       'transaction_velocity', 'cash_out_percentage',
       'suspicious_transaction_count', 'high_value_transaction_flag',
       'unusual_transaction_ratio', 'app_login_frequency',
       'app_login_anomaly_score', 'device_changes', 'ip_changes',
       'sim_card_changes', 'account_age_days', 'failed_login_attempts',
       'biometric_verification', 'blacklist_match', 'duplicate_application',
       'identity_verification_failed', 'kyc_completeness',
       'document_verification_score', 'pep_flag', 'aml_alert_count',
       'income_discrepancy', 'social_connections', 'fraudster_connections',
       'same_address_users', 'network_risk_score', 'typing_speed_anomaly',
       'click_pattern_anomaly', 'days_since_disbursement', 'bureau_score',
       'application_hour', 'income_stability_score', 'employment_tenure_years',
       'credit_utilization_ratio', 'active_loans_count',
       'total_debt_obligation', 'financial_dependency_ratio',
       'savings_balance', 'penalty_charges'],
      dtype='str')

In [15]:
encoders = {}

for col in categorical_columns:
    encoder = LabelEncoder()
    X[col] = encoder.fit_transform(X[col].astype(str))
    encoders[col] = encoder

In [16]:
scaler = StandardScaler()

X[numerical_columns] = scaler.fit_transform(X[numerical_columns])

In [17]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [18]:
print("X Train :", X_train.shape)
print("X Test  :", X_test.shape)

print()

print("y Train :", y_train.shape)
print("y Test  :", y_test.shape)

X Train : (40000, 90)
X Test  : (10000, 90)

y Train : (40000,)
y Test  : (10000,)

In [19]:
print(y_train.value_counts(normalize=True))

print()

print(y_test.value_counts(normalize=True))

is_fraud
0    0.96975
1    0.03025
Name: proportion, dtype: float64

is_fraud
0    0.9697
1    0.0303
Name: proportion, dtype: float64

In [20]:
X_train.head()

,branch_id,customer_age,gender,marital_status,education_level,occupation,annual_income,monthly_expenses,credit_score,years_with_institution,...,application_day_of_week,application_hour,income_stability_score,employment_tenure_years,credit_utilization_ratio,active_loans_count,total_debt_obligation,financial_dependency_ratio,savings_balance,penalty_charges
19408,192,0.631917,1,1,3,1,-0.855422,-0.903342,-0.377247,0.416277,...,2,-1.635489,1.624495,0.509517,0.901362,0.699467,0.019710,0.906772,0.019094,-0.399904
24170,33,-1.550955,0,1,6,1,1.161517,1.513275,1.908672,-0.178452,...,1,-0.550527,0.849543,-0.514912,-0.409401,-0.709954,-0.390142,-0.669186,-0.233537,-0.399904
2746,67,0.195343,0,1,5,1,0.522246,0.075122,0.086899,-0.920193,...,1,1.402405,1.488667,-0.573628,0.138845,-0.005243,0.440721,-0.462542,-0.191160,-0.399904
7135,96,0.544602,0,3,4,5,0.653808,1.301155,-0.307626,-0.713040,...,3,-1.418497,-0.018526,-0.908924,-0.797118,-0.005243,-1.090841,-0.727371,-0.323136,-0.399904
31610,118,-0.415862,1,2,4,1,-1.046937,-0.962728,-0.377247,1.468747,...,0,1.185412,0.490156,0.969969,-0.366732,-0.709954,-0.776589,1.931668,-0.214324,-0.399904

# Preprocessing Summary

- Duplicate records removed
- Identifier columns removed
- Post-loan leakage features removed
- Categorical variables encoded
- Numerical variables standardized
- Dataset split into training and testing sets
- Data is now ready for feature engineering and model training